language: node_js
cache:
  apt: true
  directories:
  - node_modules
node_js:
- 4.3.1
sudo: required
dist: trusty
matrix:
  fast_finish: true
  allow_failures:
  - node_js: 5.1.1
before_install:
- sudo apt-get install -y docker mysql-server mysql-client
- mysql -u root -e 'create database if not exists IOTDB_TEST;'
before_script:
- npm install -g grunt-cli
env:
  global:
  - NODE_ENV: travis
  - MYSQL_URI: mysql://root@localhost:3306/IOTDB_TEST
  - COMMIT: "${TRAVIS_COMMIT::8}"
notifications:
  slack:
    secure: WVtQtNRlSv3IXPxNKTr+EpaIDiRS7fJUot40RvWg/WOh/Sw1nxelEeIxmJ+Zll9ZUhcdjVyYCzpkENWXlCpAKFM6gMIyB2ycgYWDggl3M5Emy6vo4ARNIHwG6yaqttjnNvekuqJQV4S/FM15znM8AFvMoXfl/FK9A2V5j5oYEv2VnF3c3ohozsUBhD/JEzCDTdRlE4GCx2Tq9Mmu+NS5tDBm12QmHK1/5D721VaGkm+2DZTyH4mVxdpJXyS5bY+HmTstS+n4rmTgpdk6+VUCh1ihzou9bsfWVoVFTV1ymBef2H6VEFBkqGRUopqX/GpcYtavJHGQqxpS5AkiyRE9qTcxtFR0FCJyZdki+tjJ4Zvo3wiHWIOuqoIQPASGNe9CpZcDP1SnLqewQN8C5CF6xd6i/DWWxTchE9BVbZ8+PeH+svUTPOPaf3iaUUAakIN5tFEKOxSenAmuQTSHtxX3gKNh+Ep9yCc7eFlyDjihAjBTrTMMdbmCxEaX5PIdOOsKigciO37QZjOM0Vnk9HWTqgolKEzbKuQiHK1Y58gtge5/U7dXBrCkiwkTOq6QYJQTbgSmxJAqNBr/U4ZxRcABzx24hDh4NYJHDBk+cjp6jQIfJMrty7fUvwrq7PPlhI0mzXVsYEGIGjShmrpsjI1/Cq1RxiTUpdGTuWBoBc+zwNI=
