language: node_js
cache:
  apt: true
  directories:
  - node_modules
node_js:
  - 4.3.1
sudo: required
dist: trusty
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 5.1.1
before_install:
  - sudo apt-get install -y docker mysql-server mysql-client
  - mysql -u root -e 'create database if not exists IOTDB_TEST;'
before_script:
- npm install -g grunt-cli
env:
  global:
  - NODE_ENV: travis
  - MYSQL_URI: mysql://root@localhost:3306/IOTDB_TEST
  - COMMIT: ${TRAVIS_COMMIT::8}
